spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
  application:
    name: smart-route-prod
  datasource:
    url: jdbc:mysql://localhost:3306/smartroute_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    active:

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
    max-part-count: -1

app:
  upload:
    path: uploads\car-photos\
    license-path: uploads\licenses\